### ISSUE TITLE
Cannot add new compound if article has zero compounds

### ISSUE THREAD

**Issue by jvansan** [NPAtlas/npatlas_curator#32]
```
[2019-06-10 23:10:08,350] ERROR in app: Exception on /data/addCompound [POST]
Traceback (most recent call last):
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/conda/envs/curator/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/data/views.py", line 321, in add_compound
    article = save_data_to_article(article, data)
  File "./app/data/views.py", line 413, in save_data_to_article
    db_cmpd.name = cmpd['name']
```

**Comment by jvansan** [comment]
Fixed in : 1c2f339
